name: CI

on:
  workflow_dispatch:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

env:
  # environment vars
  DIST_ARTIFACT: dist

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Build
        run: npm run build
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          retention-days: 1

  lint:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: ESLint
        run: npm run lint:eslint
        shell: bash

      - name: Prettier
        run: npm run lint:prettier
        shell: bash

      - name: SCSS Lint
        run: npm run lint:scss
        shell: bash

  test:
    runs-on: ubuntu-latest
    needs:
      - build
      - lint
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Unit Tests
        run: npm run test
        shell: bash

  e2e-test:
    runs-on: ubuntu-latest
    needs:
      - build
      - lint
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: E2E Tests
        run: echo Run e2e tests
        shell: bash

  publish:
    if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - build
      - lint
      - test
      - e2e-test
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Copy staticwebapp.config
        run: cp staticwebapp.config.json ./dist/signup-demo/browser

      - name: Deploy to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_GLACIER_05F5AA303 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: '/dist/signup-demo/browser' # App source code path
          api_location: '' # Api source code path - optional
          output_location: '' # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
